name: "Common Setup"
description: "Setup steps for all jobs"

inputs:
  git_crypt_key:
    description: "The git-crypt key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install git-crypt
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y git-crypt

    - name: Decrypt files with git-crypt
      shell: bash
      env:
        GIT_CRYPT_KEY: ${{ inputs.git_crypt_key }}
      run: |
        echo "${GIT_CRYPT_KEY}" | base64 --decode > git-crypt-key
        git-crypt unlock git-crypt-key
        rm git-crypt-key

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: |
       sudo apt-get install -y liblpsolve55-dev libsuitesparse-dev

    - name: Set environment variables
      run: |
        echo "CGO_CFLAGS=-I/usr/include/lpsolve" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=-lm -lcolamd" >> $GITHUB_ENV

    - name: Build
      shell: bash
      run: go build ./cmd/main/main.go
