name: "Common Setup"
description: "Setup steps for all jobs"

inputs:
  git_crypt_key:
    description: "The git-crypt key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install git-crypt
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y git-crypt

    - name: Decrypt files with git-crypt
      shell: bash
      env:
        GIT_CRYPT_KEY: ${{ inputs.git_crypt_key }}
      run: |
        echo "${GIT_CRYPT_KEY}" | base64 --decode > git-crypt-key
        git-crypt unlock git-crypt-key
        rm git-crypt-key

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      shell: bash
      run: go build -v ./...
