name: "Common Setup"
description: "Setup steps for all jobs"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install git-crypt
      run: |
        sudo apt-get update
        sudo apt-get install -y git-crypt

    - name: Decrypt files with git-crypt
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      run: |
        echo "${GIT_CRYPT_KEY}" | base64 --decode > git-crypt-key
        git-crypt unlock git-crypt-key
        rm git-crypt-key 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...